//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectZip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Detail
    {
        public string Course_ID { get; set; }
        public decimal Course_No { get; set; }
        public string Subject_Code { get; set; }
        public Nullable<int> Lecture { get; set; }
        public string Course_Type { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Contact_Hours { get; set; }
        public Nullable<int> Lab { get; set; }
    
        public virtual Course_Detail Course_Detail1 { get; set; }
        public virtual Course_Detail Course_Detail2 { get; set; }
    }
}
