//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectZip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Catalog_Master
    {
        public string Subject_Code { get; set; }
        public string Subject_Desc { get; set; }
        public decimal Course_No { get; set; }
        public string Course_Desc { get; set; }
    }
}
