//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectZip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectZEntities : DbContext
    {
        public ProjectZEntities()
            : base("name=ProjectZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<College_Master> College_Master { get; set; }
        public virtual DbSet<Course_Catalog_Master> Course_Catalog_Master { get; set; }
        public virtual DbSet<Course_Detail> Course_Detail { get; set; }
        public virtual DbSet<Department_Master> Department_Master { get; set; }
    }
}
